feat: add emotes
aresrpg/data pull request #3
Opened 2022-12-23 14:23 UTC by SohKey

2022-12-23 14:26 UTC, DeltaEvo requested changes
I don't think we should put the ressource pack font file here, only a json file with the list of emote names

2022-12-26 06:48 UTC, Sceat approved these changes

2022-12-26 20:29 UTC, SohKey commented
it's ok for you to merge @DeltaEvo ?

2022-12-29 16:50 UTC, DeltaEvo approved these changes

2022-12-29 17:29 UTC, merged